[package]
name = "nordea-json-converter"
version = "0.1.0"
authors = ["Markus Lindqvist <markus.lindqvist@reaktor.com>"]

[dependencies]
chrono = "0.4.6"
csv = "1.0.2"
serde = "1.0.80"
serde_json = "1.0.33"
serde_derive = "1.0.80"
