[package]
name = "nordea-json-converter"
version = "0.1.0"
authors = ["Markus Lindqvist <markus.lindqvist@reaktor.com>"]

[dependencies]
chrono = "0.4"
csv = "1.0.0-beta.5"
serde = "1.0.7"
serde_json = "1.0"
serde_derive = "1.0.23"
